version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 530061243896.dkr.ecr.us-east-1.amazonaws.com
      - COMMIT_HASH=$(echo latest | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo Build started on `date`
      - aws s3 cp s3://buildxup-delopyment-stage/frontend/.env .
      - echo Building the Docker image...
      - docker build --cache-from 530061243896.dkr.ecr.us-east-1.amazonaws.com/stage/buildxup/frontend:cache -t 530061243896.dkr.ecr.us-east-1.amazonaws.com/stage/buildxup/frontend:latest .
      - docker tag 530061243896.dkr.ecr.us-east-1.amazonaws.com/stage/buildxup/frontend:latest 530061243896.dkr.ecr.us-east-1.amazonaws.com/stage/buildxup/frontend:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 530061243896.dkr.ecr.us-east-1.amazonaws.com/stage/buildxup/frontend:latest
      - docker push 530061243896.dkr.ecr.us-east-1.amazonaws.com/stage/buildxup/frontend:$IMAGE_TAG
      - printf '[{"name":"%s","imageUri":"%s"}]' "stage/buildxup/frontend" "530061243896.dkr.ecr.us-east-1.amazonaws.com/stage/buildxup/frontend:$IMAGE_TAG" > imagedefinitions.json

artifacts:
  files: imagedefinitions.json